name: Build App

on:
    push:
        branches:
        - master

jobs:
    sonarcloud:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2        
        - uses: sburris/dependency-check-action@master
          with:
            Project-Name: webServer
        - name: Install NPM dependencies
          run: |
            npm install --production --unsafe-perm
        - name: Archive dependency check reports
          uses: actions/upload-artifact@v1
          with:
            name: reports
            path: reports
        - name: use klar
          run: |
            wget https://github.com/optiopay/klar/releases/download/v2.4.0/klar-2.4.0-linux-amd64 -O klar
            chmod +x klar
            CLAIR_ADDR=http://clair.3r1.co:6060 ./klar docker.io/<your-username>/<your-image>:<sha-tag>            
        - name: build-push
          uses: docker/build-push-action@v1
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
            registry: docker.io
            repository: nheissler/cd
            tag_with_sha: true